# receives: 
#   - current board state 
#   - coordinate from (chess coordinate e.g. A1)
#   - coordinate to (chess coordinate e.g. A1)

# Chess move has always been generated by SF so moves should always be valid

# After moving asks the placement handler for the boardstate to validate positions

